using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using FaleMais.Repositories;
using FaleMais.Models.Entities;

namespace FaleMais.Migrations
{
    public class CidadeSeeds
    {
        public void AdicionarOuAtualizar()
        {
            EstadoRepository estadoRepository = new EstadoRepository();
            var estado = estadoRepository.RetornaPorUF("SP");

            this.CidadesDDD011(estado);
            this.CidadesDDD016(estado);
            this.CidadesDDD017(estado);
            this.CidadesDDD018(estado);
        }

        private void CidadesDDD011(Estado estado)
        {
            var cidades = new List<Cidade> {
                    new Cidade { EstadoUF = estado.UF, Nome = "Aluminio", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Aracariguama", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Arujá", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Atibaia", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Barueri", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Biritiba-Mirim", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bom Jesus dos Perdões", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bragança Paulista", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cabreúva", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Caieriras", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cajamar", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Campo Limpo Paulista", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Carapicuiba", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cotia", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Diadema", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Embu", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Embu-Guaçu", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ferraz de Vasconselos", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Francisco Morato", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Franco da Rocha", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guararema", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guarulhos", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Igaratá", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itapecerica da Serra", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itapevi", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itaquaquecetuba", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itatiba", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itu", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itupeva", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jandira", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jarinu", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Joanópolis", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jundiaí", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Juquitiba", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mairinque", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mairiporã", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mauá", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Moji das Cruzes", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Morungaba", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nazaré Paulista", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Osasco", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pedra Bela", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pinhalzinho", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Paracaia", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Parapora do Bom Jesus", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Poá", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ribeirão Pires", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rio Grande da Serra", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Salesópolis", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Salto", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Isabel", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santana de Parnaíba", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santo André", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Bernardo do Campo", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Caetano do Sul", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Lourenço da Serra", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Paulo", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Roque", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Suzano", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taboão da Serra", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tuiuti", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Vargem", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Vargem Grande Paulista", DDDNumero = "011" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Várzea Paulista", DDDNumero = "011" }
            };

            CidadeRepository cidadeRepository = new CidadeRepository();
            cidadeRepository.Insere(cidades);
        }

        private void CidadesDDD016(Estado estado)
        {
            var cidades = new List<Cidade> {
                    new Cidade { EstadoUF = estado.UF, Nome = "Autinópolis", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Américo Brasiliense", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Aramina", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Araraquara", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Barrinha", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Batatais", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Boa Esperança do Sul", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Borborema", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Brodowski", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Buritizal", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cajurú", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Candido Rodrigues", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cássias dos Coqueiros", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cravinhos", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cristais Paulista", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Dobrada", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Dourado", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Dumont", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Fernando Prestes", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Franca", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Gavião Peixoto", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guará", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guariba", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guatapará", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ibate", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ibitinga", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Iguarapava", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ipoá", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itápolis", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itirapuá", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ituverava", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jabuticabal", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jardinópolis", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jeriquara", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Luis Antônio", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Matão", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Miguelópolis", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Monte Alto", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Morro Agudo", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Motuca", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Europa", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nuporanga", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Orlândia", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Patrocínio Paulista", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pedregulho", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pitangueiras", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pontal", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Padrópolista", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Restinga", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ribeirão Bonito", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ribeirão Corrente", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ribeirão Preto", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rifaina", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rincão", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sales Oliveira", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Cruz da Esperança", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Ernestina", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Lúcia", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Rose de Viterbo", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santo Antônio da Alegria", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Carlos", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Joaquim da Barra", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São José da Bela Vista", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Simão", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Serra Azul", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Serrana", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sertãozinho", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tabatinga", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taiacú", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taiuva", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taquaral", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taquaritinga", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Trabijú", DDDNumero = "016" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Vista Alegre do Alto", DDDNumero = "011" }
                };

            CidadeRepository cidadeRepository = new CidadeRepository();
            cidadeRepository.Insere(cidades);
        }

        private void CidadesDDD017(Estado estado)
        {
            var cidades = new List<Cidade> {
                    new Cidade { EstadoUF = estado.UF, Nome = "Adolfo", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Altair", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Alfares Florence", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Américo de Campos", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Aparecida D'Oeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ariranha", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Aspásia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Auriflama", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bady Bassitt", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bálsamo", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Barretos", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bebedouro", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cajobi", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cardoso", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Catanduva", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Catiguá", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cebral", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Colina", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Colômbia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cosmirama", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Dirce Reis", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Dolcinópolis", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Elisiário", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Embauba", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Estrela D'Oeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Fernandópolis", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Floral", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Gastão Vidigal", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "General Salgado", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Gaira", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guapiacú", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guarací", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guarani D'Oeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guzolandia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ibira", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Icem", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Indiapora", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ibigua", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Irapua", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itajobi", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jaborandi", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jaci", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Jales", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "José Bonifacio", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Macaubal", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Macedonia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Magda", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Marapoama", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Marinópolis", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mendonça", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Meridiano", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mesópolis", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mira Estrela", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mirassol", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mirassolândia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Monções", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Monte Aprazível", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Monte Azul Paulista", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Neves Paulista", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nhandeara", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nipoã", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Aliança", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Canaã Paulista", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Castilho", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Granada", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Luzitania", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Novais", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Novo Horizonte", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Olímpia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Onda Verde", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Orindiuva", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ouroeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Palestina", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Palmares Paulista", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Palmares D'Oeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Paraiso", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Paranapuã", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Parisi", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Paulo de Faria", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pedranópolis", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pindorama", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pirangí", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Polomi", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pontalinda", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pontes Gestal", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Populina", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Portirendaba", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Riolândia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rubineia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sales", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Adélia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Albertina", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Clara D'Oeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sante Fé do Sul", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Rita D'Oeste", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Salete", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa da Ponte Pensa", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São Francisco", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São João das Duas Pontes", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São João de Iracema", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São José do Rio Preto", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sebastianópolis do Sul", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Severínia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tabapuã", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tanabi", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Terra Roxa", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Três Fronteiras", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tumalina", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ubarana", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Uchoa", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "União Paulista", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Urânia", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Urupes", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Valentim Gentil", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Viradouro", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Vitória Brasil", DDDNumero = "017" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Votuporanga", DDDNumero = "011" }
                };

            CidadeRepository cidadeRepository = new CidadeRepository();
            cidadeRepository.Insere(cidades);
        }

        private void CidadesDDD018(Estado estado)
        {
            var cidades = new List<Cidade> {
                    new Cidade { EstadoUF = estado.UF, Nome = "Adamantina", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Alfredo Marcondes", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Alto Alegre", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Alvares Machado", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Andradina", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Anhumas", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Aracatuba", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Assis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Avanhandava", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Barbosa", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bento de Abreu", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Bilac", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Birigui", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Borá", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Brauna", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Brejo Alegre", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Buritama", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Caiabú", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Caiua", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Candido Mota", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Castilho", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Clementina", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Coroados", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Cruzália", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Dracena", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Echaporá", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Emilianópolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Estrela do Norte", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Euclides da Cunha Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Flora Rica", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Flórida Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Florinia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Gabriel Monteiro", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Glisério", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guaraçaí", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Guararapes", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Iepe", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ilha Solteira", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Indiana", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Inubia Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Irapurú", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Itapurã", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "João Ramalho", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Junqueirópolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Lavinia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Lourdes", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Lucélia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Luziania", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Lutécia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Marabá Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Maracaí", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mariápolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Martinópolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mirandópolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Mirante do Paranapanema", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Monte Castelo", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Murutinga do Sul", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nantes", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Marandiba", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Guataporanga", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Nova Independencia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Osvaldo Cruz", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ouro Verde", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pacaembu", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Palmital", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Panoramas", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Paraguaçú Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Parapuã", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pauliceia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Padrinhas Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Penápolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pereira Barreto", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Piacatú", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Piquerobi", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pirapozinho", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Planalto", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Platina", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Pracinha", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Presidente Bernardes", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Presitente Pitácio", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Presidente Prudente", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Presidente Venceslau", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Quatá", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rancharia", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Regente Feijó", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Ribeirão dos Indios", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rinópolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rosana", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Rubiacea", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sagres", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Salmourão", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sandovalina", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santa Mercedes", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santo Anastácio", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santo Antônio do Aracanguá", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santo Expedito", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Santópolis do Aguapeí", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "São João Pau D'Alho", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Sud Mennucci", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Susanópolis", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taciba", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tarabaí", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Taruma", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Teodoro Sampaio", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Tupi Paulista", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Turiuba", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Valparaiso", DDDNumero = "018" },
                    new Cidade { EstadoUF = estado.UF, Nome = "Zacarias", DDDNumero = "011" }
                };

            CidadeRepository cidadeRepository = new CidadeRepository();
            cidadeRepository.Insere(cidades);
        }

    }
}